# NORMALIZATION PROBLEM

In [1]:
import numpy as np

In [2]:
X = np.random.randint(1,100, size = (5,5))
print(X)

[[88 44 80 28 73]
 [49 53  8  8 10]
 [55 18 10 61  1]
 [97 58 12 24 69]
 [ 7 85 90 81 43]]


In [3]:
m = X.mean()
print(m)

46.08


In [4]:
s = X.std()
print(s)

30.825859274317075


In [5]:
N = np.array(())

In [6]:
for i in X:
    for j in i:
        z = (j - m) / s
        N = np.append(N,z)

In [7]:
print(N)

[ 1.35989721 -0.06747582  1.10037484 -0.58652055  0.87329277  0.09472566
  0.22448685 -1.23532647 -1.23532647 -1.17044588  0.28936744 -0.91092351
 -1.17044588  0.48400922 -1.46240854  1.65185987  0.38668833 -1.10556529
 -0.71628174  0.74353158 -1.26776677  1.26257632  1.4247778   1.13281514
 -0.09991611]


In [8]:
N.resize(5,5)

In [9]:
print(N)

[[ 1.35989721 -0.06747582  1.10037484 -0.58652055  0.87329277]
 [ 0.09472566  0.22448685 -1.23532647 -1.23532647 -1.17044588]
 [ 0.28936744 -0.91092351 -1.17044588  0.48400922 -1.46240854]
 [ 1.65185987  0.38668833 -1.10556529 -0.71628174  0.74353158]
 [-1.26776677  1.26257632  1.4247778   1.13281514 -0.09991611]]


In [10]:
np.save('X_normalized', N)

In [11]:
data1 = np.load('X_normalized.npy')
print(data1)

[[ 1.35989721 -0.06747582  1.10037484 -0.58652055  0.87329277]
 [ 0.09472566  0.22448685 -1.23532647 -1.23532647 -1.17044588]
 [ 0.28936744 -0.91092351 -1.17044588  0.48400922 -1.46240854]
 [ 1.65185987  0.38668833 -1.10556529 -0.71628174  0.74353158]
 [-1.26776677  1.26257632  1.4247778   1.13281514 -0.09991611]]


# DIVISIBLE BY 3 PROBLEM

In [12]:
import numpy as np

In [13]:
arr = np.array((),dtype = int)

In [14]:
for i in range(1,101):
    arr = np.append(arr,i*i)

In [15]:
print(arr)

[    1     4     9    16    25    36    49    64    81   100   121   144
   169   196   225   256   289   324   361   400   441   484   529   576
   625   676   729   784   841   900   961  1024  1089  1156  1225  1296
  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209  2304
  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481  3600
  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041  5184
  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889  7056
  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025  9216
  9409  9604  9801 10000]


In [16]:
arr.resize(10,10)

In [17]:
print(arr)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [18]:
d3 = np.array((),dtype = int)
for i in arr:
    for j in i:
        if j % 3 == 0:
            d3 = np.append(d3,int(j))

In [19]:
print(d3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [20]:
np.save('div_by_3', d3)

In [21]:
data2 = np.load('div_by_3.npy')
print(data2)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
